import { cfb, gcm } from '@noble/ciphers/aes.js';
import { ed25519 } from '@noble/curves/ed25519.js';
import { argon2id } from '@noble/hashes/argon2.js';
import { hkdf } from '@noble/hashes/hkdf.js';
import { md5, ripemd160, sha1 } from '@noble/hashes/legacy.js';
import { sha224, sha256, sha384, sha512 } from '@noble/hashes/sha2.js';
import { sha3_256, sha3_512 } from '@noble/hashes/sha3.js';
import { concatBytes } from '@noble/hashes/utils.js';
import { describe, should } from '@paulmillr/jsbt/test.js';
import { base64, hex, utf8 } from '@scure/base';
import * as P from 'micro-packed';
import { deepStrictEqual, rejects, throws } from 'node:assert';
import * as pgp from '../src/pgp.ts';
import { base64armor } from '../src/utils.ts';

type SecretKey = Parameters<typeof pgp.decodeSecretKey>[1];
type SignaturePacket = Extract<pgp.Packet, { TAG: 'signature' }>['data'];
type SignatureSubpacket = SignaturePacket['unhashed'][number];
const secretKeyPacket = (packets: pgp.Packet[]): SecretKey => {
  const packet = packets.find((p): p is Extract<pgp.Packet, { TAG: 'secretKey' }> => {
    return p.TAG === 'secretKey';
  });
  if (!packet) throw new Error('missing secret-key packet');
  return packet.data;
};

// Generated by gpg (GnuPG) 2.3.3, libgcrypt 1.9.4
// First empty line inside armor is stripped to make sure there it is exact as our output
const PRIV = `-----BEGIN PGP PRIVATE KEY BLOCK-----

lIYEYZkw6BYJKwYBBAHaRw8BAQdAg0R9uOUUpnFA+owCdbOkQnyXx6h7RkDcLn9y
KcRRVVn+BwMCMbM6S1DGYvTwghmEwscM1g8Pv2ULbmZurVnlfNEB5VlURavNbf29
9vFszXdoBhIoHdvYX4Y1ueAuJhSW+ax+JEfQJQBPqzkWrNaOs1TeeLQeSm9obiBE
b2UgPGV4YW1wbGVAZXhhbXBsZS5jb20+iJQEExYKADwWIQSuELnesWtuPXyJZvoo
TA4wFkYIeAUCYZkw6AIbAwULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQ
KEwOMBZGCHhe/gEAtLhHurG3qUum79lMT6yX1I/5P+h+j+9nkRurixFBz5oA/0w8
T0MkaQWp1JDCfO8Y5nlE2lTseJ86zPCwZCRm0pUJnIsEYZkw6BIKKwYBBAGXVQEF
AQEHQAhe17QiohzSF1A+VCkF2QESiwqEowxiINg3Yd5AN1gsAwEIB/4HAwIFDB8+
Rr/MjfCrVL5H3GXorEeKotHsewx8M3ak5uDVsWvtyEIow5XyD294xHRPjC40+YT2
mK7abrzh66kcntOO6XNo4M1fffbftCqCfCC6iHgEGBYKACAWIQSuELnesWtuPXyJ
ZvooTA4wFkYIeAUCYZkw6AIbDAAKCRAoTA4wFkYIeIY/AQDYev3xwXBq+qRn3SNH
5ogrjYMghF1HweCCmclLKTTBUQD/VFncDGnQeXtsQHrFkkliTWy9Lwi/WPBtha4u
p2xTgwU=
=ipHm
-----END PGP PRIVATE KEY BLOCK-----
`;

const PUB = `-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEYZkw6BYJKwYBBAHaRw8BAQdAg0R9uOUUpnFA+owCdbOkQnyXx6h7RkDcLn9y
KcRRVVm0HkpvaG4gRG9lIDxleGFtcGxlQGV4YW1wbGUuY29tPoiUBBMWCgA8FiEE
rhC53rFrbj18iWb6KEwOMBZGCHgFAmGZMOgCGwMFCwkIBwIDIgIBBhUKCQgLAgQW
AgMBAh4HAheAAAoJEChMDjAWRgh4Xv4BALS4R7qxt6lLpu/ZTE+sl9SP+T/ofo/v
Z5Ebq4sRQc+aAP9MPE9DJGkFqdSQwnzvGOZ5RNpU7HifOszwsGQkZtKVCbg4BGGZ
MOgSCisGAQQBl1UBBQEBB0AIXte0IqIc0hdQPlQpBdkBEosKhKMMYiDYN2HeQDdY
LAMBCAeIeAQYFgoAIBYhBK4Qud6xa249fIlm+ihMDjAWRgh4BQJhmTDoAhsMAAoJ
EChMDjAWRgh4hj8BANh6/fHBcGr6pGfdI0fmiCuNgyCEXUfB4IKZyUspNMFRAP9U
WdwMadB5e2xAesWSSWJNbL0vCL9Y8G2Fri6nbFODBQ==
=d0Ek
-----END PGP PUBLIC KEY BLOCK-----
`;

const USER = 'John Doe <example@example.com>';
const PWD = '123456789';
const CREATED = 1637429480;
const Hash = { md5, ripemd160, sha224, sha256, sha384, sha512, sha3_256, sha3_512, sha1 };
const EXPBIAS6 = (count: number) => (16 + (count & 15)) << ((count >> 4) + 6);
const bytesToBigInt = (bytes: Uint8Array) => BigInt(`0x${hex.encode(bytes) || '0'}`);
const U16BE = (n: number) => Uint8Array.of(n >>> 8, n & 0xff);
const U32BE = (n: number) => Uint8Array.of(n >>> 24, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff);
type PubKeyPacket = P.UnwrapCoder<typeof pgp.PubKeyPacket>;
type Argon2S2KPacket = {
  TAG: 'symmetric_key_encrypted_session_key';
  data: {
    enc: string;
    S2K: { TAG: 'argon2'; data: { salt: Uint8Array; t: number; p: number; encodedM: number } };
    encryptedSessionKey: Uint8Array;
  };
  newFormat?: true;
};
type EncryptedProtectedDataPacket = {
  TAG: 'encryptedProtectedData';
  data: Uint8Array;
  newFormat?: true;
};
const deriveKey = (
  hash: keyof typeof Hash,
  len: number,
  password: Uint8Array,
  salt?: Uint8Array,
  count?: number
) => {
  count = count === undefined ? 0 : EXPBIAS6(count);
  const data = salt ? concatBytes(salt, password) : password;
  let out = Uint8Array.of();
  const hashC = Hash[hash];
  const rounds = Math.ceil(len / hashC.outputLen);
  for (let r = 0; r < rounds; r++) {
    const h = hashC.create();
    if (r > 0) h.update(new Uint8Array(r));
    for (let c = Math.max(count, data.length); c > 0; ) {
      const take = Math.min(c, data.length);
      h.update(data.subarray(0, take));
      c -= take;
    }
    out = concatBytes(out, h.digest());
  }
  return out.subarray(0, len);
};
const secretChecksum = (data: Uint8Array) => {
  let checksum = 0;
  for (let i = 0; i < data.length; i++) checksum += data[i];
  return checksum % 65536;
};
const checksumSecret = (secret: Uint8Array) => {
  const encoded = pgp.mpi.encode(bytesToBigInt(secret));
  return concatBytes(encoded, U16BE(secretChecksum(encoded)));
};
const checksumOpaqueSecret = (secret: Uint8Array) => {
  const encoded = pgp.opaquempi.encode(secret);
  return concatBytes(encoded, U16BE(secretChecksum(encoded)));
};
const keyFingerprintV6 = (packet: PubKeyPacket) => {
  const body = pgp.PubKeyPacket.encode(packet);
  return hex.encode(sha256(concatBytes(Uint8Array.of(0x9b), U32BE(body.length), body)));
};
const partialPacket = (head: number, body: Uint8Array, lengths: number[]) => {
  let pos = 0;
  const chunks = [Uint8Array.of(head)];
  for (const len of lengths) {
    chunks.push(Uint8Array.of(0xe0 | Math.log2(len)), body.subarray(pos, pos + len));
    pos += len;
  }
  chunks.push(pgp.PacketLen.encode(body.length - pos), body.subarray(pos));
  return concatBytes(...chunks);
};
const indexOfBytes = (buf: Uint8Array, needle: Uint8Array) => {
  for (let i = 0; i <= buf.length - needle.length; i++) {
    let match = true;
    for (let j = 0; j < needle.length; j++) {
      if (buf[i + j] === needle[j]) continue;
      match = false;
      break;
    }
    if (match) return i;
  }
  return -1;
};
const aesCfb = (key: Uint8Array, iv: Uint8Array, data: Uint8Array) => cfb(key, iv).encrypt(data);

const crc24 = (data: Uint8Array) => {
  let crc = 0xb704ce;
  for (const byte of data) {
    crc ^= byte << 16;
    for (let i = 0; i < 8; i++) {
      crc <<= 1;
      if (crc & 0x1000000) crc ^= 0x1864cfb;
    }
  }
  return crc & 0xffffff;
};

const armor = (bytes: Uint8Array, label = 'PGP PUBLIC KEY BLOCK') => {
  const body = base64.encode(bytes).replace(/(.{64})/g, '$1\n');
  const sum = crc24(bytes);
  const crc = base64.encode(Uint8Array.of(sum >> 16, (sum >> 8) & 0xff, sum & 0xff));
  return `-----BEGIN ${label}-----\n\n${body}\n=${crc}\n-----END ${label}-----\n`;
};

const armorRaw = (text: string) =>
  base64.decode(
    text
      .trim()
      .split('\n')
      .filter(
        (line) =>
          line && !line.startsWith('-----') && !line.startsWith('=') && !/^[A-Za-z-]+: /.test(line)
      )
      .join('')
  );
const RFC9580_A1_SECRET = hex.decode(
  '1a8b1ff05ded48e18bf50166c664ab023ea70003d78d9e41f5758a91d850f8d2'
);
const RFC9580_A1_CREATED = 0x53f35f0b;
const RFC9580_A1_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xjMEU/NfCxYJKwYBBAHaRw8BAQdAPwmJlL3ZFu1AUxl5NOSofIBzOhKA1i+AEJku
Q+47JAY=
-----END PGP PUBLIC KEY BLOCK-----`;
const RFC9580_A2_SIGNATURE = `-----BEGIN PGP SIGNATURE-----

iF4EABYIAAYFAlX5X5UACgkQjP3hIZeWWpr2IgD/VvkMypjiECY3vZg/2xbBMd/S
ftgr9N3lYG4NdWrtM2YBANCcT6EVJ/A44PV/IgHYLy6iyQMyZfps60iehUuuYbQE
-----END PGP SIGNATURE-----`;
const RFC9580_A3_PUBLIC_KEY = `-----BEGIN PGP PUBLIC KEY BLOCK-----

xioGY4d/4xsAAAAg+U2nu0jWCmHlZ3BqZYfQMxmZu52JGggkLq2EVD34laPCsQYf
GwoAAABCBYJjh3/jAwsJBwUVCg4IDAIWAAKbAwIeCSIhBssYbE8GCaaX5NUt+mxy
KwwfHifBilZwj2Ul7Ce62azJBScJAgcCAAAAAK0oIBA+LX0ifsDm185Ecds2v8lw
gyU2kCcUmKfvBXbAf6rhRYWzuQOwEn7E/aLwIwRaLsdry0+VcallHhSu4RN6HWaE
QsiPlR4zxP/TP7mhfVEe7XWPxtnMUMtf15OyA51YBM4qBmOHf+MZAAAAIIaTJINn
+eUBXbki+PSAld2nhJh/LVmFsS+60WyvXkQ1wpsGGBsKAAAALAWCY4d/4wKbDCIh
BssYbE8GCaaX5NUt+mxyKwwfHifBilZwj2Ul7Ce62azJAAAAAAQBIKbpGG2dWTX8
j+VjFM21J0hqWlEg+bdiojWnKfA5AQpWUWtnNwDEM0g12vYxoWM8Y81W+bHBw805
I8kWVkXU6vFOi+HWvv/ira7ofJu16NnoUkhclkUrk0mXubZvyl4GBg==
-----END PGP PUBLIC KEY BLOCK-----`;
const RFC9580_A4_PRIVATE_KEY = `-----BEGIN PGP PRIVATE KEY BLOCK-----

xUsGY4d/4xsAAAAg+U2nu0jWCmHlZ3BqZYfQMxmZu52JGggkLq2EVD34laMAGXKB
exK+cH6NX1hs5hNhIB00TrJmosgv3mg1ditlsLfCsQYfGwoAAABCBYJjh3/jAwsJ
BwUVCg4IDAIWAAKbAwIeCSIhBssYbE8GCaaX5NUt+mxyKwwfHifBilZwj2Ul7Ce6
2azJBScJAgcCAAAAAK0oIBA+LX0ifsDm185Ecds2v8lwgyU2kCcUmKfvBXbAf6rh
RYWzuQOwEn7E/aLwIwRaLsdry0+VcallHhSu4RN6HWaEQsiPlR4zxP/TP7mhfVEe
7XWPxtnMUMtf15OyA51YBMdLBmOHf+MZAAAAIIaTJINn+eUBXbki+PSAld2nhJh/
LVmFsS+60WyvXkQ1AE1gCk95TUR3XFeibg/u/tVY6a//1q0NWC1X+yui3O24wpsG
GBsKAAAALAWCY4d/4wKbDCIhBssYbE8GCaaX5NUt+mxyKwwfHifBilZwj2Ul7Ce6
2azJAAAAAAQBIKbpGG2dWTX8j+VjFM21J0hqWlEg+bdiojWnKfA5AQpWUWtnNwDE
M0g12vYxoWM8Y81W+bHBw805I8kWVkXU6vFOi+HWvv/ira7ofJu16NnoUkhclkUr
k0mXubZvyl4GBg==
-----END PGP PRIVATE KEY BLOCK-----`;
const RFC9580_A5_LOCKED_PRIVATE_KEY = `-----BEGIN PGP PRIVATE KEY BLOCK-----

xYIGY4d/4xsAAAAg+U2nu0jWCmHlZ3BqZYfQMxmZu52JGggkLq2EVD34laP9JgkC
FARdb9ccngltHraRe25uHuyuAQQVtKipJ0+r5jL4dacGWSAheCWPpITYiyfyIOPS
3gIDyg8f7strd1OB4+LZsUhcIjOMpVHgmiY/IutJkulneoBYwrEGHxsKAAAAQgWC
Y4d/4wMLCQcFFQoOCAwCFgACmwMCHgkiIQbLGGxPBgmml+TVLfpscisMHx4nwYpW
cI9lJewnutmsyQUnCQIHAgAAAACtKCAQPi19In7A5tfORHHbNr/JcIMlNpAnFJin
7wV2wH+q4UWFs7kDsBJ+xP2i8CMEWi7Ha8tPlXGpZR4UruETeh1mhELIj5UeM8T/
0z+5oX1RHu11j8bZzFDLX9eTsgOdWATHggZjh3/jGQAAACCGkySDZ/nlAV25Ivj0
gJXdp4SYfy1ZhbEvutFsr15ENf0mCQIUBA5hhGgp2oaavg6mFUXcFMwBBBUuE8qf
9Ock+xwusd+GAglBr5LVyr/lup3xxQvHXFSjjA2haXfoN6xUGRdDEHI6+uevKjVR
v5oAxgu7eJpaXNjCmwYYGwoAAAAsBYJjh3/jApsMIiEGyxhsTwYJppfk1S36bHIr
DB8eJ8GKVnCPZSXsJ7rZrMkAAAAABAEgpukYbZ1ZNfyP5WMUzbUnSGpaUSD5t2Ki
Nacp8DkBClZRa2c3AMQzSDXa9jGhYzxjzVb5scHDzTkjyRZWRdTq8U6L4da+/+Kt
ruh8m7Xo2ehSSFyWRSuTSZe5tm/KXgYG
-----END PGP PRIVATE KEY BLOCK-----`;
const RFC9580_A6_TEXT = `What we need from the grocery store:

- tofu
- vegetables
- noodles
`;
const RFC9580_A6_CLEARTEXT = `-----BEGIN PGP SIGNED MESSAGE-----

What we need from the grocery store:

- - tofu
- - vegetables
- - noodles

-----BEGIN PGP SIGNATURE-----

wpgGARsKAAAAKQWCY5ijYyIhBssYbE8GCaaX5NUt+mxyKwwfHifBilZwj2Ul7Ce6
2azJAAAAAGk2IHZJX1AhiJD39eLuPBgiUU9wUA9VHYblySHkBONKU/usJ9BvuAqo
/FvLFuGWMbKAdA+epq7V4HOtAPlBWmU8QOd6aud+aSunHQaaEJ+iTFjP2OMW0KBr
NK2ay45cX1IVAQ==
-----END PGP SIGNATURE-----`;
const RFC9580_A7_INLINE_MESSAGE = `-----BEGIN PGP MESSAGE-----

xEYGAQobIHZJX1AhiJD39eLuPBgiUU9wUA9VHYblySHkBONKU/usyxhsTwYJppfk
1S36bHIrDB8eJ8GKVnCPZSXsJ7rZrMkBy0p1AAAAAABXaGF0IHdlIG5lZWQgZnJv
bSB0aGUgZ3JvY2VyeSBzdG9yZToKCi0gdG9mdQotIHZlZ2V0YWJsZXMKLSBub29k
bGVzCsKYBgEbCgAAACkFgmOYo2MiIQbLGGxPBgmml+TVLfpscisMHx4nwYpWcI9l
JewnutmsyQAAAABpNiB2SV9QIYiQ9/Xi7jwYIlFPcFAPVR2G5ckh5ATjSlP7rCfQ
b7gKqPxbyxbhljGygHQPnqau1eBzrQD5QVplPEDnemrnfmkrpx0GmhCfokxYz9jj
FtCgazStmsuOXF9SFQE=
-----END PGP MESSAGE-----`;
const RFC9580_A8_MESSAGE = `-----BEGIN PGP MESSAGE-----

wV0GIQYSyD8ecG9jCP4VGkF3Q6HwM3kOk+mXhIjR2zeNqZMIhRmHzxjV8bU/gXzO
WgBM85PMiVi93AZfJfhK9QmxfdNnZBjeo1VDeVZheQHgaVf7yopqR6W1FT6NOrfS
aQIHAgZhZBZTW+CwcW1g4FKlbExAf56zaw76/prQoN+bAzxpohup69LA7JW/Vp0l
yZnuSj3hcFj0DfqLTGgr4/u717J+sPWbtQBfgMfG9AOIwwrUBqsFE9zW+f1zdlYo
bhF30A+IitsxxA==
-----END PGP MESSAGE-----`;
const RFC9580_A9_MESSAGE = `-----BEGIN PGP MESSAGE-----

w0AGHgcBCwMIpa5XnR/F2Cv/aSJPkZmTs1Bvo7WaanPP+MXvxfQcV/tU4cImgV14
KPX5LEVOtl6+AKtZhsaObnxV0mkCBwEGn/kOOzIZZPOkKRPI3MZhkyUBUifvt+rq
pJ8EwuZ0F11KPSJu1q/LnKmsEiwUcOEcY9TAqyQcapOK1Iv5mlqZuQu6gyXeYQR1
QCWKt5Wala0FHdqW6xVDHf719eIlXKeCYVRuM5o=
-----END PGP MESSAGE-----`;
const RFC9580_A10_MESSAGE = `-----BEGIN PGP MESSAGE-----

wz8GHQcCCwMIVqKY0vXjZFP/z8xcEWZO2520JZDX3EawckG2EsOBLP/76gDyNHsl
ZBEj+IeuYNT9YU4IN9gZ02zSaQIHAgYgpmH3MfyaMDK1YjMmAn46XY21dI6+/wsM
WRDQns3WQf+f04VidYA1vEl1TOG/P/+n2tCjuBBPUTPPQqQQCoPu9MobSAGohGv0
K82nyM6dZeIS8wHLzZj9yt5pSod61CRzI/boVw==
-----END PGP MESSAGE-----`;
const RFC9580_A11_MESSAGE = `-----BEGIN PGP MESSAGE-----

wzwGGgcDCwMI6dOXhbIHAAj/tC58SD70iERXyzcmubPbn/d25fTZpAlS4kRymIUa
v/91Jt8t1VRBdXmneZ/SaQIHAwb8uUSQvLmLvcnRBsYJAmaUD3LontwhtVlrFXax
Ae0Pn/xvxtZbv9JNzQeQlm5tHoWjAFN4TLHYtqBpnvEhVaeyrWJYUxtXZR/Xd3kS
+pXjXZtAIW9ppMJI2yj/QzHxYykHOZ5v+Q==
-----END PGP MESSAGE-----`;
const RFC4880_ARMORED_MESSAGE_WITH_HEADER = `-----BEGIN PGP MESSAGE-----
Version: OpenPrivacy 0.99

yDgBO22WxBHv7O8X7O/jygAEzol56iUKiXmV+XmpCtmpqQUKiQrFqclFqUDBovzS
vBSFjNSiVHsuAA==
=njUN
-----END PGP MESSAGE-----`;
const RFC9580_A3_FINGERPRINT = 'cb186c4f0609a697e4d52dfa6c722b0c1f1e27c18a56708f6525ec27bad9acc9';
const RFC9580_ARGON2_MESSAGES = [
  {
    enc: 'aes128',
    armor: `-----BEGIN PGP MESSAGE-----
Comment: Encrypted using AES with 128-bit key
Comment: Session key: 01FE16BBACFD1E7B78EF3B865187374F

wycEBwScUvg8J/leUNU1RA7N/zE2AQQVnlL8rSLPP5VlQsunlO+ECxHSPgGYGKY+
YJz4u6F+DDlDBOr5NRQXt/KJIf4m4mOlKyC/uqLbpnLJZMnTq3o79GxBTdIdOzhH
XfA3pqV4mTzF
-----END PGP MESSAGE-----`,
  },
  {
    enc: 'aes192',
    armor: `-----BEGIN PGP MESSAGE-----
Comment: Encrypted using AES with 192-bit key
Comment: Session key: 27006DAE68E509022CE45A14E569E91001C2955...
Comment: Session key: ...AF8DFE194

wy8ECAThTKxHFTRZGKli3KNH4UP4AQQVhzLJ2va3FG8/pmpIPd/H/mdoVS5VBLLw
F9I+AdJ1Sw56PRYiKZjCvHg+2bnq02s33AJJoyBexBI4QKATFRkyez2gldJldRys
LVg77Mwwfgl2n/d572WciAM=
-----END PGP MESSAGE-----`,
  },
  {
    enc: 'aes256',
    armor: `-----BEGIN PGP MESSAGE-----
Comment: Encrypted using AES with 256-bit key
Comment: Session key: BBEDA55B9AAE63DAC45D4F49D89DACF4AF37FEF...
Comment: Session key: ...C13BAB2F1F8E18FB74580D8B0

wzcECQS4eJUgIG/3mcaILEJFpmJ8AQQVnZ9l7KtagdClm9UaQ/Z6M/5roklSGpGu
623YmaXezGj80j4B+Ku1sgTdJo87X1Wrup7l0wJypZls21Uwd67m9koF60eefH/K
95D1usliXOEm8ayQJQmZrjf6K6v9PWwqMQ==
-----END PGP MESSAGE-----`,
  },
] as const;
const mutateAEADPreference = (pub: string, id: number) => {
  const raw = armorRaw(pub);
  const pos = raw.findIndex(
    (_, i, arr) =>
      arr[i] === 0x03 && arr[i + 1] === 0x22 && arr[i + 2] === 0x02 && arr[i + 3] === 0x01
  );
  deepStrictEqual(pos >= 0, true);
  const mutated = raw.slice();
  mutated[pos + 2] = id;
  return armor(mutated);
};
const mutateAEADPreferenceSubpacket = (pub: string, id: number) => {
  const raw = armorRaw(pub);
  const pos = raw.findIndex(
    (_, i, arr) =>
      arr[i] === 0x03 && arr[i + 1] === 0x22 && arr[i + 2] === 0x02 && arr[i + 3] === 0x01
  );
  deepStrictEqual(pos >= 0, true);
  const mutated = raw.slice();
  mutated[pos + 1] = id;
  return armor(mutated);
};
const mutateEncryptionPreference = (pub: string, id: number) => {
  const raw = armorRaw(pub);
  const pos = indexOfBytes(raw, Uint8Array.of(0x05, 0x0b, 0x09, 0x08, 0x07, 0x02));
  deepStrictEqual(pos >= 0, true);
  const mutated = raw.slice();
  mutated[pos + 2] = id;
  return armor(mutated);
};
const appendSignatureMPI = (sig: string) => {
  const raw = armorRaw(sig);
  deepStrictEqual((raw[0] >> 2) & 0x0f, 2);
  deepStrictEqual(raw[0] & 0x03, 0);
  const extra = Uint8Array.of(0x00, 0x01, 0x01);
  const bodyLen = raw[1];
  deepStrictEqual(bodyLen + 2, raw.length);
  raw[1] = bodyLen + extra.length;
  return armor(concatBytes(raw, extra), 'PGP SIGNATURE');
};
const dropSignatureCreationTime = (sig: string) => {
  const raw = armorRaw(sig);
  deepStrictEqual((raw[0] >> 2) & 0x0f, 2);
  deepStrictEqual(raw[0] & 0x03, 0);
  const body = raw.subarray(2);
  let hashedLen = (body[4] << 8) | body[5];
  const hashedStart = 6;
  const hashedEnd = hashedStart + hashedLen;
  let pos = hashedStart;
  for (; pos < hashedEnd; ) {
    const first = body[pos];
    let len;
    let lenLen;
    if (first < 192) {
      len = first;
      lenLen = 1;
    } else if (first <= 254) {
      len = ((first - 192) << 8) + body[pos + 1] + 192;
      lenLen = 2;
    } else {
      len = (body[pos + 1] << 24) | (body[pos + 2] << 16) | (body[pos + 3] << 8) | body[pos + 4];
      lenLen = 5;
    }
    if ((body[pos + lenLen] & 0x7f) === 2) break;
    pos += lenLen + len;
  }
  deepStrictEqual(pos < hashedEnd, true);
  const first = body[pos];
  const len = first < 192 ? first : first <= 254 ? ((first - 192) << 8) + body[pos + 1] + 192 : 0;
  const lenLen = first < 192 ? 1 : first <= 254 ? 2 : 5;
  hashedLen -= lenLen + len;
  body[4] = hashedLen >>> 8;
  body[5] = hashedLen & 0xff;
  const next = concatBytes(
    raw.subarray(0, 2),
    body.subarray(0, pos),
    body.subarray(pos + lenLen + len)
  );
  next[1] -= lenLen + len;
  return armor(next, 'PGP SIGNATURE');
};
const signDetachedWithHash = (
  privateKey: Uint8Array,
  data: Uint8Array,
  fingerprint: string,
  hash: keyof typeof Hash
) => {
  const head = {
    version: undefined,
    type: 'binary',
    algo: 'EdDSA',
    hash,
    hashed: [
      { TAG: 'issuerFingerprint', data: { version: undefined, fingerprint } },
      { TAG: 'signatureCreationTime', data: 0 },
    ],
  };
  const sigData = pgp.__TESTS.SignatureHead.encode(head);
  const digest = Hash[hash](
    concatBytes(data, sigData, Uint8Array.of(0x04, 0xff), U32BE(sigData.length))
  );
  const sig = ed25519.sign(digest, privateKey);
  return pgp.sigArmor.encode([
    {
      TAG: 'signature',
      data: {
        head,
        unhashed: [{ TAG: 'issuer', data: fingerprint.slice(-16) }],
        hashPrefix: digest.subarray(0, 2),
        sig: [bytesToBigInt(sig.subarray(0, 32)), bytesToBigInt(sig.subarray(32))],
      },
    },
  ]);
};
const cleartextSignature = (text: string) => {
  const start = text.indexOf('-----BEGIN PGP SIGNATURE-----');
  if (start < 0) throw new Error('missing cleartext signature block');
  return text.slice(start);
};
const rfc9580A3PublicKey = () => pgp.pubArmor.decode(RFC9580_A3_PUBLIC_KEY)[0].data.algo.data.pub;
const packetOverview = (packet) => {
  const data = packet.data;
  if (packet.TAG === 'publicKey' || packet.TAG === 'publicSubkey')
    return {
      TAG: packet.TAG,
      version: data.version,
      created: data.created,
      algo: data.algo.TAG,
      pub: hex.encode(data.algo.data.pub),
    };
  if (packet.TAG === 'secretKey' || packet.TAG === 'secretSubkey')
    return {
      TAG: packet.TAG,
      version: data.pub.version,
      created: data.pub.created,
      algo: data.pub.algo.TAG,
      pub: hex.encode(data.pub.algo.data.pub),
      protection: data.type.TAG,
      enc: data.type.data.enc,
      aead: data.type.data.aead,
      s2k: data.type.data.S2K?.TAG,
      ivLen: data.type.data.iv?.length,
      secretLen: data.type.data.secret.length,
    };
  if (packet.TAG === 'signature')
    return {
      TAG: packet.TAG,
      version: data.head.version,
      type: data.head.type,
      algo: data.head.algo,
      hash: data.head.hash,
      hashed: data.head.hashed.map((s) => s.TAG),
      unhashed: data.unhashed.map((s) => s.TAG),
      saltLen: data.salt?.length,
      sigLen: data.sig.length,
    };
  if (packet.TAG === 'onePassSignature')
    return {
      TAG: packet.TAG,
      version: data.version,
      type: data.type,
      algo: data.algo,
      hash: data.hash,
      saltLen: data.salt.length,
      fingerprint: data.fingerprint,
      last: data.last,
    };
  if (packet.TAG === 'literalData')
    return {
      TAG: packet.TAG,
      format: data.format,
      filename: data.filename,
      created: data.created,
      data: utf8.encode(data.data),
    };
  if (packet.TAG === 'public_key_encrypted_session_key')
    return {
      TAG: packet.TAG,
      version: data.version,
      fingerprint: data.fingerprint.fingerprint,
      algo: data.algo,
      ephemeral: hex.encode(data.ephemeral),
      encryptedSessionKeyLen: data.encryptedSessionKey.length,
    };
  if (packet.TAG === 'symmetric_key_encrypted_session_key')
    return {
      TAG: packet.TAG,
      version: data.version,
      enc: data.enc,
      aead: data.aead,
      s2k: data.S2K.TAG,
      ivLen: data.iv?.length,
      encryptedSessionKeyLen: data.encryptedSessionKey.length,
      tagLen: data.tag?.length,
    };
  if (packet.TAG === 'encryptedProtectedData')
    return { TAG: packet.TAG, version: data[0], len: data.length };
  return { TAG: packet.TAG };
};

describe('pgp', () => {
  should('OID', () => {
    deepStrictEqual(hex.encode(pgp.oid.encode('1.2.840.10045.3.1.7')), '2a8648ce3d030107');
    deepStrictEqual(pgp.oid.decode(pgp.oid.encode('1.2.840.10045.3.1.7')), '1.2.840.10045.3.1.7');
    deepStrictEqual(hex.encode(pgp.oid.encode('1.3.132.0.34')), '2b81040022');
    deepStrictEqual(pgp.oid.decode(hex.decode('2b81040022')), '1.3.132.0.34');
    deepStrictEqual(hex.encode(pgp.oid.encode('1.3.132.0.35')), '2b81040023');
    deepStrictEqual(pgp.oid.decode(hex.decode('2b81040023')), '1.3.132.0.35');
    deepStrictEqual(pgp.oid.encode('1.2.0'), Uint8Array.of(0x2a, 0x00));
    deepStrictEqual(pgp.oid.decode(Uint8Array.of(0x2a, 0x00)), '1.2.0');
    deepStrictEqual(pgp.oid.encode('2.48.1'), Uint8Array.of(0x81, 0x00, 0x01));
    deepStrictEqual(pgp.oid.decode(Uint8Array.of(0x81, 0x00, 0x01)), '2.48.1');
    deepStrictEqual(hex.encode(pgp.oid.encode('1.3.132.0.10')), '2b8104000a');
    throws(() => pgp.oid.encode('1'));
    throws(() => pgp.oid.encode('3.0'));
    throws(() => pgp.oid.decode(Uint8Array.of(0x80, 0x2a)));
    throws(() => pgp.oid.decode(Uint8Array.of(0x2a, 0x80, 0x00)));
  });
  should('MPI canonical boundaries', () => {
    deepStrictEqual(pgp.mpi.encode(0n), Uint8Array.of(0, 0));
    deepStrictEqual(pgp.mpi.decode(Uint8Array.of(0, 0)), 0n);
    deepStrictEqual(pgp.mpi.encode(1n), Uint8Array.of(0, 1, 1));
    deepStrictEqual(pgp.mpi.decode(Uint8Array.of(0, 1, 1)), 1n);
    deepStrictEqual(pgp.mpi.encode(5n), Uint8Array.of(0, 3, 5));
    deepStrictEqual(pgp.mpi.decode(Uint8Array.of(0, 3, 5)), 5n);
    deepStrictEqual(pgp.mpi.encode(511n), Uint8Array.of(0, 9, 1, 0xff));
    deepStrictEqual(pgp.mpi.decode(Uint8Array.of(0, 9, 1, 0xff)), 511n);
    const rfc1991Big = 2n ** 255n + 7n;
    deepStrictEqual(
      pgp.mpi.encode(rfc1991Big),
      hex.decode('01008000000000000000000000000000000000000000000000000000000000000007')
    );
    deepStrictEqual(
      pgp.mpi.decode(
        hex.decode('01008000000000000000000000000000000000000000000000000000000000000007')
      ),
      rfc1991Big
    );
    throws(() => pgp.mpi.decode(Uint8Array.of(0, 2, 1)));
    throws(() => pgp.mpi.decode(Uint8Array.of(0, 1, 0x81)));
  });
  should('One-Pass Signature packet', () => {
    const raw = hex.decode('900d030008161a9b09743c2e0b5e01');
    const packet = [
      {
        TAG: 'onePassSignature',
        data: {
          version: undefined,
          type: 'binary',
          hash: 'sha256',
          algo: 'EdDSA',
          keyId: '1a9b09743c2e0b5e',
          last: true,
        },
      },
    ];
    deepStrictEqual(pgp.Stream.decode(raw), packet);
    deepStrictEqual(pgp.Stream.encode(packet), raw);
    throws(() => pgp.Stream.decode(Uint8Array.of(0x90, 0x00)));
  });
  should('PacketHead supports legacy and OpenPGP format headers', () => {
    const { PacketHead } = pgp.__TESTS;
    deepStrictEqual(PacketHead.decode(Uint8Array.of(0x90)), {
      magic: undefined,
      version: undefined,
      tag: 'onePassSignature',
      lenType: 0,
    });
    deepStrictEqual(
      PacketHead.encode({ tag: 'onePassSignature', lenType: 0 }),
      Uint8Array.of(0x90)
    );
    deepStrictEqual(PacketHead.decode(Uint8Array.of(0xd2)), {
      magic: undefined,
      version: undefined,
      newFormat: true,
      tag: 'encryptedProtectedData',
    });
    deepStrictEqual(
      PacketHead.encode({ tag: 'encryptedProtectedData', newFormat: true }),
      Uint8Array.of(0xd2)
    );
    deepStrictEqual(PacketHead.encode({ tag: 'userAttribute', lenType: 0 }), Uint8Array.of(0xd1));
  });
  should('Stream decodes OpenPGP-format packet headers', () => {
    const raw = hex.decode('cd0561203c613e');
    const packet = [{ TAG: 'userId', data: 'a <a>', newFormat: true }];
    deepStrictEqual(pgp.Stream.decode(raw), packet);
    deepStrictEqual(pgp.Stream.encode(packet), raw);
  });
  should('User ID packets require well-formed UTF-8', () => {
    deepStrictEqual(pgp.Stream.decode(Uint8Array.of(0xcd, 3, 0xe2, 0x82, 0xac)), [
      { TAG: 'userId', data: '€', newFormat: true },
    ]);
    throws(() => pgp.Stream.decode(Uint8Array.of(0xcd, 1, 0xff)));
    throws(() => pgp.Stream.encode([{ TAG: 'userId', data: '\uD800', newFormat: true }]));
  });
  should('PacketLen', () => {
    deepStrictEqual(pgp.PacketLen.encode(100), new Uint8Array([0x64]));
    deepStrictEqual(pgp.PacketLen.encode(1723), new Uint8Array([0xc5, 0xfb]));
    deepStrictEqual(pgp.PacketLen.encode(8383), new Uint8Array([0xdf, 0xff]));
    deepStrictEqual(pgp.PacketLen.encode(100000), new Uint8Array([0xff, 0x00, 0x01, 0x86, 0xa0]));

    deepStrictEqual(pgp.PacketLen.decode(new Uint8Array([0x64])), 100);
    deepStrictEqual(pgp.PacketLen.decode(new Uint8Array([0xc5, 0xfb])), 1723);
    deepStrictEqual(pgp.PacketLen.decode(new Uint8Array([0xdf, 0xff])), 8383);
    deepStrictEqual(pgp.PacketLen.decode(new Uint8Array([0xff, 0x00, 0x01, 0x86, 0xa0])), 100000);
  });
  should('Stream decodes and preserves RFC 9580 partial body lengths', () => {
    const literal = Uint8Array.from({ length: 99994 }, (_, i) => 0x41 + (i % 26));
    const body = concatBytes(Uint8Array.of(0x62, 0, 0, 0, 0, 0), literal);
    const raw = partialPacket(0xcb, body, [32768, 2, 1, 65536]);
    const packets = pgp.Stream.decode(raw);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
    deepStrictEqual(
      {
        TAG: packets[0].TAG,
        newFormat: packets[0].newFormat,
        partialLengths: packets[0].partialLengths,
        format: packets[0].data.format,
        filename: packets[0].data.filename,
        created: packets[0].data.created,
        dataLen: packets[0].data.data.length,
        first: hex.encode(packets[0].data.data.subarray(0, 8)),
        last: hex.encode(packets[0].data.data.subarray(-8)),
      },
      {
        TAG: 'literalData',
        newFormat: true,
        partialLengths: [32768, 2, 1, 65536],
        format: 'binary',
        filename: '',
        created: 0,
        dataLen: 99994,
        first: '4142434445464748',
        last: '5152535455565758',
      }
    );
    throws(() => pgp.Stream.decode(partialPacket(0xcb, body.subarray(0, 2), [1])), /512/);
    throws(
      () => pgp.Stream.decode(partialPacket(0xcd, body.subarray(0, 512), [512])),
      /data packets/
    );
  });
  should('RFC 9580 Appendix A.1 version 4 Ed25519Legacy key vector', () => {
    const publicKey = ed25519.getPublicKey(RFC9580_A1_SECRET);
    deepStrictEqual(
      hex.encode(publicKey),
      '3f098994bdd916ed4053197934e4a87c80733a1280d62f8010992e43ee3b2406'
    );
    const id = pgp.getKeyId(RFC9580_A1_SECRET, RFC9580_A1_CREATED);
    deepStrictEqual(
      {
        fingerprint: id.fingerprint,
        keyId: id.keyId,
      },
      {
        fingerprint: 'c959bdbafa32a2f89a153b678cfde12197965a9a',
        keyId: '8cfde12197965a9a',
      }
    );
    const raw = armorRaw(RFC9580_A1_PUBLIC_KEY);
    const packets = [
      {
        TAG: 'publicKey',
        data: {
          version: undefined,
          created: RFC9580_A1_CREATED,
          algo: {
            TAG: 'EdDSA',
            data: {
              curve: 'ed25519',
              pub: bytesToBigInt(concatBytes(Uint8Array.of(0x40), publicKey)),
            },
          },
        },
        newFormat: true,
      },
    ];
    deepStrictEqual(
      hex.encode(raw),
      'c6330453f35f0b16092b06010401da470f010107403f098994bdd916ed4053197934e4a87c80733a1280d62f8010992e43ee3b2406'
    );
    deepStrictEqual(pgp.pubArmor.decode(RFC9580_A1_PUBLIC_KEY), packets);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
  });
  should('RFC 9580 Appendix A.2 version 4 Ed25519Legacy signature vector', () => {
    const publicKey = ed25519.getPublicKey(RFC9580_A1_SECRET);
    const raw = armorRaw(RFC9580_A2_SIGNATURE);
    const packets = pgp.sigArmor.decode(RFC9580_A2_SIGNATURE);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
    deepStrictEqual(packets, [
      {
        TAG: 'signature',
        data: {
          head: {
            version: undefined,
            type: 'binary',
            algo: 'EdDSA',
            hash: 'sha256',
            hashed: [{ TAG: 'signatureCreationTime', data: 1442406293 }],
          },
          unhashed: [{ TAG: 'issuer', data: '8cfde12197965a9a' }],
          hashPrefix: Uint8Array.of(0xf6, 0x22),
          sig: [
            bytesToBigInt(
              hex.decode('56f90cca98e2102637bd983fdb16c131dfd27ed82bf4dde5606e0d756aed3366')
            ),
            bytesToBigInt(
              hex.decode('d09c4fa11527f038e0f57f2201d82f2ea2c9033265fa6ceb489e854bae61b404')
            ),
          ],
        },
      },
    ]);
    deepStrictEqual(
      pgp.verifyDetached(publicKey, RFC9580_A2_SIGNATURE, utf8.decode('OpenPGP')),
      true
    );
  });
  should('RFC 9580 Appendix A.3 version 6 certificate vector parses and round-trips', () => {
    const raw = armorRaw(RFC9580_A3_PUBLIC_KEY);
    const packets = pgp.pubArmor.decode(RFC9580_A3_PUBLIC_KEY);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
    const [primary, directSig, subkey, subkeySig] = packets;
    deepStrictEqual(packets.map(packetOverview), [
      {
        TAG: 'publicKey',
        version: 6,
        created: 1669824483,
        algo: 'Ed25519',
        pub: 'f94da7bb48d60a61e567706a6587d0331999bb9d891a08242ead84543df895a3',
      },
      {
        TAG: 'signature',
        version: 6,
        type: 'key',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: [
          'signatureCreationTime',
          'preferredEncryptionAlgorithms',
          'preferredHashAlgorithms',
          'preferredCompressionAlgorithms',
          'keyFlags',
          'features',
          'issuerFingerprint',
          'preferredAEADCiphersuites',
        ],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
      {
        TAG: 'publicSubkey',
        version: 6,
        created: 1669824483,
        algo: 'X25519',
        pub: '8693248367f9e5015db922f8f48095dda784987f2d5985b12fbad16caf5e4435',
      },
      {
        TAG: 'signature',
        version: 6,
        type: 'subkeyBinding',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: ['signatureCreationTime', 'keyFlags', 'issuerFingerprint'],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
    ]);
    const direct = pgp.__TESTS.verifyData(
      directSig.data.head,
      primary.data,
      directSig.data.sig,
      primary.data.algo.data.pub,
      directSig.data.salt
    );
    const binding = pgp.__TESTS.verifyData(
      subkeySig.data.head,
      { pubKey: primary.data, subKey: subkey.data },
      subkeySig.data.sig,
      primary.data.algo.data.pub,
      subkeySig.data.salt
    );
    deepStrictEqual(
      {
        primaryFingerprint: keyFingerprintV6(primary.data),
        subkeyFingerprint: keyFingerprintV6(subkey.data),
        direct: { verified: direct.verified, hashPrefix: hex.encode(direct.hashPrefix) },
        binding: { verified: binding.verified, hashPrefix: hex.encode(binding.hashPrefix) },
      },
      {
        primaryFingerprint: RFC9580_A3_FINGERPRINT,
        subkeyFingerprint: '12c83f1e706f6308fe151a417743a1f033790e93e9978488d1db378da9930885',
        direct: { verified: true, hashPrefix: hex.encode(directSig.data.hashPrefix) },
        binding: { verified: true, hashPrefix: hex.encode(subkeySig.data.hashPrefix) },
      }
    );
  });
  should('RFC 9580 Appendix A.4-A.5 version 6 secret-key vectors parse and round-trip', () => {
    const unlockedRaw = armorRaw(RFC9580_A4_PRIVATE_KEY);
    const unlocked = pgp.privArmor.decode(RFC9580_A4_PRIVATE_KEY);
    deepStrictEqual(pgp.Stream.encode(unlocked), unlockedRaw);
    deepStrictEqual(unlocked.map(packetOverview), [
      {
        TAG: 'secretKey',
        version: 6,
        created: 1669824483,
        algo: 'Ed25519',
        pub: 'f94da7bb48d60a61e567706a6587d0331999bb9d891a08242ead84543df895a3',
        protection: 'plain',
        enc: undefined,
        aead: undefined,
        s2k: undefined,
        ivLen: undefined,
        secretLen: 32,
      },
      {
        TAG: 'signature',
        version: 6,
        type: 'key',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: [
          'signatureCreationTime',
          'preferredEncryptionAlgorithms',
          'preferredHashAlgorithms',
          'preferredCompressionAlgorithms',
          'keyFlags',
          'features',
          'issuerFingerprint',
          'preferredAEADCiphersuites',
        ],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
      {
        TAG: 'secretSubkey',
        version: 6,
        created: 1669824483,
        algo: 'X25519',
        pub: '8693248367f9e5015db922f8f48095dda784987f2d5985b12fbad16caf5e4435',
        protection: 'plain',
        enc: undefined,
        aead: undefined,
        s2k: undefined,
        ivLen: undefined,
        secretLen: 32,
      },
      {
        TAG: 'signature',
        version: 6,
        type: 'subkeyBinding',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: ['signatureCreationTime', 'keyFlags', 'issuerFingerprint'],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
    ]);
    const lockedRaw = armorRaw(RFC9580_A5_LOCKED_PRIVATE_KEY);
    const locked = pgp.privArmor.decode(RFC9580_A5_LOCKED_PRIVATE_KEY);
    deepStrictEqual(pgp.Stream.encode(locked), lockedRaw);
    deepStrictEqual(
      locked.map(packetOverview).filter((p) => p.TAG === 'secretKey' || p.TAG === 'secretSubkey'),
      [
        {
          TAG: 'secretKey',
          version: 6,
          created: 1669824483,
          algo: 'Ed25519',
          pub: 'f94da7bb48d60a61e567706a6587d0331999bb9d891a08242ead84543df895a3',
          protection: 'aead',
          enc: 'aes256',
          aead: 'OCB',
          s2k: 'argon2',
          ivLen: 15,
          secretLen: 48,
        },
        {
          TAG: 'secretSubkey',
          version: 6,
          created: 1669824483,
          algo: 'X25519',
          pub: '8693248367f9e5015db922f8f48095dda784987f2d5985b12fbad16caf5e4435',
          protection: 'aead',
          enc: 'aes256',
          aead: 'OCB',
          s2k: 'argon2',
          ivLen: 15,
          secretLen: 48,
        },
      ]
    );
  });
  should('RFC 9580 Appendix A.5 locked secret-key decrypt reaches AEAD boundary', () => {
    const locked = pgp.privArmor.decode(RFC9580_A5_LOCKED_PRIVATE_KEY);
    throws(
      () => pgp.decodeSecretKey('correct horse battery staple', locked[0].data),
      /OCB not implemented in noble-ciphers, available in awasm\/noble/
    );
  });
  should('v6 AEAD secret-key decrypt supports Argon2 plus GCM', () => {
    const [packet] = pgp.privArmor.decode(RFC9580_A4_PRIVATE_KEY);
    const plain = packet.data;
    const secret = plain.type.data.secret;
    const salt = Uint8Array.from({ length: 16 }, (_, i) => i + 1);
    const nonce = Uint8Array.from({ length: 12 }, (_, i) => 0xa0 + i);
    const S2K = { TAG: 'argon2', data: { salt, t: 1, p: 1, encodedM: 3 } };
    const s2kKey = argon2id(utf8.decode('secret'), salt, { t: 1, p: 1, m: 1 << 3, dkLen: 32 });
    const info = Uint8Array.of(0xc5, 6, 9, 3);
    const key = hkdf(sha256, s2kKey, undefined, info, 32);
    const aad = concatBytes(Uint8Array.of(0xc5), pgp.PubKeyPacket.encode(plain.pub));
    const encrypted = gcm(key, nonce, aad).encrypt(secret);
    const locked = {
      ...plain,
      type: {
        TAG: 'aead',
        data: { enc: 'aes256', aead: 'GCM', S2K, iv: nonce, secret: encrypted },
      },
    };
    const tampered = structuredClone(locked);
    tampered.type.data.secret[0] ^= 1;
    deepStrictEqual(pgp.decodeSecretKey('secret', locked), bytesToBigInt(secret));
    deepStrictEqual(pgp.decodeSecretKey('secret', locked, 'secretKey'), bytesToBigInt(secret));
    throws(() => pgp.decodeSecretKey('secret', locked, 'secretSubkey'), /invalid ghash tag/);
    throws(() => pgp.decodeSecretKey('secret', tampered), /invalid ghash tag/);
  });
  should('v6 CFB secret-key packets use usage 254 with parameter lengths', () => {
    const [packet] = pgp.privArmor.decode(RFC9580_A4_PRIVATE_KEY);
    const plain = packet.data as {
      pub: PubKeyPacket;
      type: { TAG: 'plain'; data: { secret: Uint8Array } };
    };
    const salt = Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const iv = Uint8Array.from({ length: 16 }, (_, i) => 0xb0 + i);
    const S2K = { TAG: 'salted', data: { hash: 'sha256', salt } };
    const kek = deriveKey('sha256', 16, utf8.decode('secret'), salt);
    const clear = concatBytes(plain.type.data.secret, sha1(plain.type.data.secret));
    const encrypted = aesCfb(kek, iv, clear);
    const locked = {
      pub: plain.pub,
      type: { TAG: 'encrypted', data: { enc: 'aes128', S2K, iv, secret: encrypted } },
    };
    const s2k = Uint8Array.of(1, 8, ...salt);
    const body = concatBytes(
      pgp.PubKeyPacket.encode(plain.pub),
      // RFC 9580 §5.5.3: v6 usage 254 has a parameter-length octet before
      // cipher, S2K-specifier-length, S2K specifier, and CFB IV.
      Uint8Array.of(254, 1 + 1 + s2k.length + iv.length, 7, s2k.length),
      s2k,
      iv,
      encrypted
    );
    const raw = concatBytes(Uint8Array.of(0xc5), pgp.PacketLen.encode(body.length), body);
    const packets = [{ TAG: 'secretKey', data: locked, newFormat: true }];
    deepStrictEqual(pgp.Stream.decode(raw), packets);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
    deepStrictEqual(pgp.decodeSecretKey('secret', locked), bytesToBigInt(plain.type.data.secret));
  });
  should('v6 secret-key decrypt rejects weak S2K hashes', () => {
    const [packet] = pgp.privArmor.decode(RFC9580_A4_PRIVATE_KEY);
    const plain = packet.data as {
      pub: PubKeyPacket;
      type: { TAG: 'plain'; data: { secret: Uint8Array } };
    };
    const salt = Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const iv = Uint8Array.from({ length: 16 }, (_, i) => 0xc0 + i);
    const S2K = { TAG: 'salted', data: { hash: 'sha1', salt } };
    const kek = deriveKey('sha1', 16, utf8.decode('secret'), salt);
    const cfb = {
      pub: plain.pub,
      type: {
        TAG: 'encrypted',
        data: {
          enc: 'aes128',
          S2K,
          iv,
          secret: aesCfb(
            kek,
            iv,
            concatBytes(plain.type.data.secret, sha1(plain.type.data.secret))
          ),
        },
      },
    };
    const nonce = Uint8Array.from({ length: 12 }, (_, i) => 0xd0 + i);
    const info = Uint8Array.of(0xc5, 6, 7, 3);
    const aeadKey = hkdf(sha256, kek, undefined, info, 16);
    const aad = concatBytes(Uint8Array.of(0xc5), pgp.PubKeyPacket.encode(plain.pub));
    const aead = {
      pub: plain.pub,
      type: {
        TAG: 'aead',
        data: {
          enc: 'aes128',
          aead: 'GCM',
          S2K,
          iv: nonce,
          secret: gcm(aeadKey, nonce, aad).encrypt(plain.type.data.secret),
        },
      },
    };
    throws(() => pgp.decodeSecretKey('secret', cfb), /weak S2K hash/);
    throws(() => pgp.decodeSecretKey('secret', aead, 'secretKey'), /weak S2K hash/);
  });
  should('RFC 9580 Appendix A.6-A.7 version 6 signed-message vectors parse and verify', () => {
    const signature = cleartextSignature(RFC9580_A6_CLEARTEXT);
    const sigRaw = armorRaw(signature);
    const sigPackets = pgp.sigArmor.decode(signature);
    deepStrictEqual(pgp.Stream.encode(sigPackets), sigRaw);
    deepStrictEqual(sigPackets.map(packetOverview), [
      {
        TAG: 'signature',
        version: 6,
        type: 'text',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: ['signatureCreationTime', 'issuerFingerprint'],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
    ]);
    deepStrictEqual(
      pgp.verifyDetached(rfc9580A3PublicKey(), signature, RFC9580_A6_TEXT, RFC9580_A3_FINGERPRINT),
      true
    );
    const raw = armorRaw(RFC9580_A7_INLINE_MESSAGE);
    const packets = pgp.Stream.decode(raw);
    deepStrictEqual(pgp.Stream.encode(packets), raw);
    deepStrictEqual(packets.map(packetOverview), [
      {
        TAG: 'onePassSignature',
        version: 6,
        type: 'text',
        algo: 'Ed25519',
        hash: 'sha512',
        saltLen: 32,
        fingerprint: RFC9580_A3_FINGERPRINT,
        last: true,
      },
      {
        TAG: 'literalData',
        format: 'utf8',
        filename: '',
        created: 0,
        data: RFC9580_A6_TEXT,
      },
      {
        TAG: 'signature',
        version: 6,
        type: 'text',
        algo: 'Ed25519',
        hash: 'sha512',
        hashed: ['signatureCreationTime', 'issuerFingerprint'],
        unhashed: [],
        saltLen: 32,
        sigLen: 64,
      },
    ]);
    deepStrictEqual(
      pgp.verifyDetached(
        rfc9580A3PublicKey(),
        pgp.sigArmor.encode([packets[2]]),
        utf8.encode(packets[1].data.data),
        RFC9580_A3_FINGERPRINT
      ),
      true
    );
  });
  should('RFC 9580 Appendix A.8-A.11 v6 AEAD message packet vectors parse and round-trip', () => {
    const parsed = [
      ['A.8', RFC9580_A8_MESSAGE],
      ['A.9', RFC9580_A9_MESSAGE],
      ['A.10', RFC9580_A10_MESSAGE],
      ['A.11', RFC9580_A11_MESSAGE],
    ].map(([name, message]) => {
      const raw = armorRaw(message);
      const packets = pgp.Stream.decode(raw);
      deepStrictEqual(pgp.Stream.encode(packets), raw);
      return { name, packets: packets.map(packetOverview) };
    });
    deepStrictEqual(parsed, [
      {
        name: 'A.8',
        packets: [
          {
            TAG: 'public_key_encrypted_session_key',
            version: 6,
            fingerprint: '12c83f1e706f6308fe151a417743a1f033790e93e9978488d1db378da9930885',
            algo: 'X25519',
            ephemeral: '87cf18d5f1b53f817cce5a004cf393cc8958bddc065f25f84af509b17dd36764',
            encryptedSessionKeyLen: 24,
          },
          { TAG: 'encryptedProtectedData', version: 2, len: 105 },
        ],
      },
      {
        name: 'A.9',
        packets: [
          {
            TAG: 'symmetric_key_encrypted_session_key',
            version: 6,
            enc: 'aes128',
            aead: 'EAX',
            s2k: 'iterated',
            ivLen: 16,
            encryptedSessionKeyLen: 16,
            tagLen: 16,
          },
          { TAG: 'encryptedProtectedData', version: 2, len: 105 },
        ],
      },
      {
        name: 'A.10',
        packets: [
          {
            TAG: 'symmetric_key_encrypted_session_key',
            version: 6,
            enc: 'aes128',
            aead: 'OCB',
            s2k: 'iterated',
            ivLen: 15,
            encryptedSessionKeyLen: 16,
            tagLen: 16,
          },
          { TAG: 'encryptedProtectedData', version: 2, len: 105 },
        ],
      },
      {
        name: 'A.11',
        packets: [
          {
            TAG: 'symmetric_key_encrypted_session_key',
            version: 6,
            enc: 'aes128',
            aead: 'GCM',
            s2k: 'iterated',
            ivLen: 12,
            encryptedSessionKeyLen: 16,
            tagLen: 16,
          },
          { TAG: 'encryptedProtectedData', version: 2, len: 105 },
        ],
      },
    ]);
  });
  should('RFC 9580 Appendix A.8 v6 X25519 PKESK unwrap reaches OCB boundary', () => {
    const [pkesk, seipd] = pgp.Stream.decode(armorRaw(RFC9580_A8_MESSAGE));
    const secretPackets = pgp.privArmor.decode(RFC9580_A4_PRIVATE_KEY);
    const secretSubkey = secretPackets[2].data;
    const sessionKey = pgp.__TESTS.decryptV6PKESK(secretSubkey.type.data.secret, pkesk.data);
    deepStrictEqual(hex.encode(sessionKey), 'dd708f6fa1ed65114d68d2343e7c2f1d');
    throws(
      () => pgp.__TESTS.decryptV2SEIPD(sessionKey, seipd.data),
      /OCB not implemented in noble-ciphers, available in awasm\/noble/
    );
  });
  should('RFC 9580 Appendix A.11 v6 AEAD-GCM message vector decrypts', () => {
    const [skesk, seipd] = pgp.Stream.decode(armorRaw(RFC9580_A11_MESSAGE));
    const sessionKey = pgp.__TESTS.decryptV6SKESK(utf8.decode('password'), skesk.data);
    const decrypted = pgp.__TESTS.decryptV2SEIPD(sessionKey, seipd.data);
    deepStrictEqual(
      {
        sessionKey: hex.encode(sessionKey),
        packets: decrypted.map(packetOverview),
        padding: hex.encode(decrypted[1].data),
      },
      {
        sessionKey: '1936fc8568980274bb900d8319360c77',
        packets: [
          {
            TAG: 'literalData',
            format: 'binary',
            filename: '',
            created: 0,
            data: 'Hello, world!',
          },
          { TAG: 'padding' },
        ],
        padding: '1ce2269a9eddef81032172b7ed7c',
      }
    );
  });
  should('RFC 9580 Appendix A.9-A.10 unsupported AEAD modes fail at decrypt boundary', () => {
    const [eax] = pgp.Stream.decode(armorRaw(RFC9580_A9_MESSAGE));
    const [ocb] = pgp.Stream.decode(armorRaw(RFC9580_A10_MESSAGE));
    throws(
      () => pgp.__TESTS.decryptV6SKESK(utf8.decode('password'), eax.data),
      /EAX not implemented/
    );
    throws(
      () => pgp.__TESTS.decryptV6SKESK(utf8.decode('password'), ocb.data),
      /OCB not implemented in noble-ciphers, available in awasm\/noble/
    );
  });
  should('RFC 4880 §6.6 armor headers are skipped before base64 decode', () => {
    const messageArmor = base64armor('PGP MESSAGE', 64, P.bytes(null), (data) => {
      const sum = crc24(data);
      return Uint8Array.of(sum >> 16, (sum >> 8) & 0xff, sum & 0xff);
    });
    deepStrictEqual(
      hex.encode(messageArmor.decode(RFC4880_ARMORED_MESSAGE_WITH_HEADER)),
      'c838013b6d96c411efecef17ecefe3ca0004ce8979ea250a897995f979a90ad9a9a9050a890ac5a9c945a940c1a2fcd2bc14858cd4a2547b2e00'
    );
  });
  should('Signature subpacket lengths use the full two-octet range', () => {
    const { SignatureSubpacketLen } = pgp.__TESTS;
    deepStrictEqual(SignatureSubpacketLen.decode(Uint8Array.of(0xe0, 0x00)), 8384);
    deepStrictEqual(SignatureSubpacketLen.encode(8384), Uint8Array.of(0xe0, 0x00));
    deepStrictEqual(SignatureSubpacketLen.decode(Uint8Array.of(0xfe, 0xff)), 16319);
    deepStrictEqual(SignatureSubpacketLen.encode(16319), Uint8Array.of(0xfe, 0xff));
    const hashes = new Uint8Array(8383).fill(8);
    const createdAt = Uint8Array.of(5, 2, 0, 0, 0, 0);
    const subpacket = concatBytes(Uint8Array.of(0xe0, 0x00, 21), hashes);
    const body = concatBytes(
      Uint8Array.of(4, 0, 22, 8),
      U16BE(createdAt.length + subpacket.length),
      createdAt,
      subpacket,
      U16BE(0),
      Uint8Array.of(0, 0),
      pgp.mpi.encode(0n),
      pgp.mpi.encode(0n)
    );
    const raw = concatBytes(Uint8Array.of(0x89), U16BE(body.length), body);
    const decoded = pgp.Stream.decode(raw);
    deepStrictEqual(decoded[0].data.head.hashed, [
      { TAG: 'signatureCreationTime', data: 0 },
      { TAG: 'preferredHashAlgorithms', data: Array(8383).fill('sha256') },
    ]);
    deepStrictEqual(pgp.Stream.encode(decoded), raw);
    throws(() => pgp.PacketLen.decode(Uint8Array.of(0xe0, 0x00)));
  });
  should('Signature subpacket critical bit is separate from type id', () => {
    const createdAt = Uint8Array.of(5, 2, 0, 0, 0, 0);
    const criticalKeyFlags = Uint8Array.of(2, 0x9b, 0x03);
    const body = concatBytes(
      Uint8Array.of(4, 0, 22, 8),
      U16BE(createdAt.length + criticalKeyFlags.length),
      createdAt,
      criticalKeyFlags,
      U16BE(0),
      Uint8Array.of(0, 0),
      pgp.mpi.encode(0n),
      pgp.mpi.encode(0n)
    );
    const raw = concatBytes(Uint8Array.of(0x88, body.length), body);
    const decoded = pgp.Stream.decode(raw);
    deepStrictEqual(decoded[0].data.head.hashed, [
      { TAG: 'signatureCreationTime', data: 0 },
      {
        TAG: 'keyFlags',
        data: {
          _r: false,
          shared: false,
          auth: false,
          split: false,
          encrypt: false,
          encryptComm: false,
          sign: true,
          certify: true,
        },
        critical: true,
      },
    ]);
    deepStrictEqual(pgp.Stream.encode(decoded), raw);
  });
  should('Signature fingerprint subpacket version matches signature version', () => {
    const v4Fingerprint = '00'.repeat(20);
    const v6Fingerprint = '00'.repeat(32);
    const badV6 = {
      version: 6,
      type: 'binary',
      algo: 'Ed25519',
      hash: 'sha512',
      hashed: [
        { TAG: 'signatureCreationTime', data: 0 },
        { TAG: 'issuerFingerprint', data: { fingerprint: v4Fingerprint } },
      ],
    };
    const badV4 = {
      type: 'binary',
      algo: 'EdDSA',
      hash: 'sha512',
      hashed: [
        { TAG: 'signatureCreationTime', data: 0 },
        { TAG: 'intendedRecipientFingerprint', data: { version: 6, fingerprint: v6Fingerprint } },
      ],
    };
    throws(() => pgp.__TESTS.SignatureHead.encode(badV6));
    throws(() => pgp.__TESTS.SignatureHead.encode(badV4));
    const createdAt = Uint8Array.of(5, 2, 0, 0, 0, 0);
    const issuerFingerprint = Uint8Array.of(22, 33, 4, ...new Uint8Array(20));
    throws(() =>
      pgp.__TESTS.SignatureHead.decode(
        concatBytes(
          Uint8Array.of(6, 0, 27, 10),
          U32BE(createdAt.length + issuerFingerprint.length),
          createdAt,
          issuerFingerprint
        )
      )
    );
  });
  should('v6 Ed25519 signatures reject sub-256-bit digests', () => {
    const seed = new Uint8Array(32);
    const head = {
      version: 6,
      type: 'binary',
      algo: 'Ed25519',
      hash: 'sha224',
      hashed: [
        { TAG: 'signatureCreationTime', data: 0 },
        { TAG: 'issuerFingerprint', data: { version: 6, fingerprint: '00'.repeat(32) } },
      ],
    };
    throws(() =>
      pgp.__TESTS.verifyData(
        head,
        new Uint8Array(),
        new Uint8Array(64),
        ed25519.getPublicKey(seed),
        new Uint8Array(16)
      )
    );
  });
  should('PGP', () => {
    const edPriv = hex.decode('6c18b9d6dc5d18a933c704c56ed8165a0651b27856ce3345f52f2921666dcef1');
    const cvPriv = hex.decode('58cf48afad21cbf3e2d904387df28a1385c8a1b790f28e04ca7eb721fd6c0d6b');
    const edSalt = hex.decode('31b33a4b50c662f4');
    const edIV = hex.decode('821984c2c70cd60f0fbf650b6e666ead');
    const cvSalt = hex.decode('050c1f3e46bfcc8d');
    const cvIV = hex.decode('ab54be47dc65e8ac478aa2d1ec7b0c7c');
    const pubKey = pgp.formatPublic(edPriv, cvPriv, USER, CREATED);
    const privKey = pgp.formatPrivate(
      edPriv,
      cvPriv,
      USER,
      PWD,
      CREATED,
      edSalt,
      edIV,
      cvSalt,
      cvIV
    );
    deepStrictEqual(pgp.pubArmor.decode(pubKey), pgp.pubArmor.decode(PUB), 'publicKey (stream)');
    deepStrictEqual(pubKey, PUB, 'publicKey (armor)');
    deepStrictEqual(
      pgp.privArmor.decode(privKey),
      pgp.privArmor.decode(PRIV),
      'privateKey (stream)'
    );
    deepStrictEqual(privKey, PRIV, 'privateKey (armor)');
    deepStrictEqual(
      pgp.decodeSecretKey(PWD, pgp.privArmor.decode(PRIV)[0].data),
      48893474592257195969419733099033914136114698516948265455201948185088704237297n
    );
    deepStrictEqual(
      pgp.decodeSecretKey(PWD, pgp.privArmor.decode(PRIV)[3].data),
      48421196023274373923070909897586368745762760188967824324892067105939602853720n
    );
  });
  const NAME_EMAIL = 'a <a>';
  const seed = hex.decode('29f47c314ee8b1c77a0b7e4c0043a04a20af46f10132855b79f9ff6c4f8a8ed9');
  should('AEAD preference subpacket enum', () => {
    const { publicKey } = pgp.getKeys(seed, NAME_EMAIL, PWD, 0);
    const pub = pgp.pubArmor.decode(mutateAEADPreference(publicKey, 3));
    const sig = pub.find((p) => p.TAG === 'signature');
    const prefs = sig.data.head.hashed.find((s) => s.TAG === 'preferredAEADAlgorithms')?.data;
    deepStrictEqual(prefs, ['GCM', 'EAX']);
    throws(() => pgp.pubArmor.decode(mutateAEADPreference(publicKey, 0)));
  });
  should('signature subpacket supports final AEAD ciphersuites and legacy AEAD algorithms', () => {
    const { publicKey } = pgp.getKeys(seed, NAME_EMAIL, PWD, 0);
    const packets = pgp.pubArmor.decode(publicKey);
    const sig = packets.find((p) => p.TAG === 'signature');
    const suite = {
      TAG: 'preferredAEADCiphersuites',
      data: [
        { enc: 'aes256', aead: 'OCB' },
        { enc: 'aes256', aead: 'GCM' },
        { enc: 'camellia256', aead: 'OCB' },
      ],
    };
    sig.data.head.hashed.push(suite);
    const encoded = pgp.pubArmor.encode(packets);
    const raw = armorRaw(encoded);
    deepStrictEqual(
      indexOfBytes(raw, Uint8Array.of(0x07, 0x27, 0x09, 0x02, 0x09, 0x03, 0x0d, 0x02)) >= 0,
      true
    );
    const decoded = pgp.pubArmor.decode(encoded);
    const hashed = decoded.find((p) => p.TAG === 'signature').data.head.hashed;
    deepStrictEqual(hashed.find((s) => s.TAG === 'preferredAEADAlgorithms')?.data, ['OCB', 'EAX']);
    deepStrictEqual(hashed.find((s) => s.TAG === 'preferredAEADCiphersuites')?.data, suite.data);
    throws(() => pgp.pubArmor.decode(mutateAEADPreferenceSubpacket(publicKey, 37)));
    throws(() => pgp.pubArmor.decode(mutateAEADPreferenceSubpacket(publicKey, 38)));
  });
  should('S2K parses RFC 9580 Argon2 specifiers', () => {
    const { S2K, S2KEnum } = pgp.__TESTS;
    const salt = Uint8Array.from([
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
      0x0f,
    ]);
    const encoded = Uint8Array.from([0x04, ...salt, 0x01, 0x04, 0x15]);
    const decoded = { TAG: 'argon2', data: { salt, t: 1, p: 4, encodedM: 21 } };
    deepStrictEqual(S2KEnum.decode(Uint8Array.of(4)), 'argon2');
    deepStrictEqual(S2KEnum.encode('argon2'), Uint8Array.of(4));
    throws(() => S2KEnum.decode(Uint8Array.of(2)));
    deepStrictEqual(S2K.decode(encoded), decoded);
    deepStrictEqual(S2K.encode(decoded), encoded);
    throws(() => S2K.decode(Uint8Array.from([0x04, ...salt, 0x00, 0x04, 0x15])));
    throws(() => S2K.decode(Uint8Array.from([0x04, ...salt, 0x01, 0x00, 0x15])));
    throws(() => S2K.decode(Uint8Array.from([0x04, ...salt, 0x01, 0x04, 0x04])));
    throws(() => S2K.decode(Uint8Array.from([0x04, ...salt, 0x01, 0x04, 0x20])));
  });
  should('RFC 9580 Appendix A.12 Argon2 message vectors parse and round-trip', () => {
    // The appendix vectors use encoded_m=21, i.e. 2 GiB of Argon2 memory.
    // Keep the normal suite bounded to OpenPGP packet/S2K vector bytes and
    // leave Argon2 primitive vectors to noble-hashes.
    const parsed = RFC9580_ARGON2_MESSAGES.map(({ enc, armor }) => {
      const raw = armorRaw(armor);
      const packets = pgp.Stream.decode(raw) as [Argon2S2KPacket, EncryptedProtectedDataPacket];
      deepStrictEqual(pgp.Stream.encode(packets), raw);
      const [skesk, seipd] = packets;
      return {
        enc,
        tags: packets.map((p) => p.TAG),
        skesk: {
          enc: skesk.data.enc,
          s2k: skesk.data.S2K.TAG,
          salt: hex.encode(skesk.data.S2K.data.salt),
          t: skesk.data.S2K.data.t,
          p: skesk.data.S2K.data.p,
          encodedM: skesk.data.S2K.data.encodedM,
          encryptedSessionKey: hex.encode(skesk.data.encryptedSessionKey),
        },
        seipd: hex.encode(seipd.data),
      };
    });
    deepStrictEqual(parsed, [
      {
        enc: 'aes128',
        tags: ['symmetric_key_encrypted_session_key', 'encryptedProtectedData'],
        skesk: {
          enc: 'aes128',
          s2k: 'argon2',
          salt: '9c52f83c27f95e50d535440ecdff3136',
          t: 1,
          p: 4,
          encodedM: 21,
          encryptedSessionKey: '9e52fcad22cf3f956542cba794ef840b11',
        },
        seipd:
          '019818a63e609cf8bba17e0c394304eaf9351417b7f28921fe26e263a52b20bfbaa2dba672c964c9d3ab7a3bf46c414dd21d3b38475df037a6a578993cc5',
      },
      {
        enc: 'aes192',
        tags: ['symmetric_key_encrypted_session_key', 'encryptedProtectedData'],
        skesk: {
          enc: 'aes192',
          s2k: 'argon2',
          salt: 'e14cac4715345918a962dca347e143f8',
          t: 1,
          p: 4,
          encodedM: 21,
          encryptedSessionKey: '8732c9daf6b7146f3fa66a483ddfc7fe6768552e5504b2f017',
        },
        seipd:
          '01d2754b0e7a3d16222998c2bc783ed9b9ead36b37dc0249a3205ec4123840a0131519327b3da095d265751cac2d583beccc307e09769ff779ef659c8803',
      },
      {
        enc: 'aes256',
        tags: ['symmetric_key_encrypted_session_key', 'encryptedProtectedData'],
        skesk: {
          enc: 'aes256',
          s2k: 'argon2',
          salt: 'b8789520206ff799c6882c4245a6627c',
          t: 1,
          p: 4,
          encodedM: 21,
          encryptedSessionKey: '9d9f65ecab5a81d0a59bd51a43f67a33fe6ba249521a91aeeb6dd899a5decc68fc',
        },
        seipd:
          '01f8abb5b204dd268f3b5f55abba9ee5d30272a5996cdb553077aee6f64a05eb479e7c7fcaf790f5bac9625ce126f1ac90250999ae37fa2babfd3d6c2a31',
      },
    ]);
  });
  should('symmetric preference subpacket enum includes Camellia', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const camelliaPrefs = {
      TAG: 'preferredEncryptionAlgorithms',
      data: ['camellia128', 'camellia192', 'camellia256'],
    };
    deepStrictEqual(SignatureSubpacket.decode(Uint8Array.of(4, 11, 11, 12, 13)), camelliaPrefs);
    deepStrictEqual(SignatureSubpacket.encode(camelliaPrefs), Uint8Array.of(4, 11, 11, 12, 13));
    const { publicKey } = pgp.getKeys(seed, NAME_EMAIL, PWD, 0);
    const pub = pgp.pubArmor.decode(mutateEncryptionPreference(publicKey, 13));
    const sig = pub.find((p) => p.TAG === 'signature');
    const prefs = sig.data.head.hashed.find((s) => s.TAG === 'preferredEncryptionAlgorithms')?.data;
    deepStrictEqual(prefs, ['camellia256', 'aes192', 'aes128', 'tripledes']);
  });
  should('Signature subpacket supports Signers User ID', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const data = 'Generated <generated@example.com>';
    const subpacket = { TAG: 'signersUserID' as const, data };
    const encoded = concatBytes(Uint8Array.of(1 + utf8.decode(data).length, 28), utf8.decode(data));
    deepStrictEqual(SignatureSubpacket.decode(encoded), subpacket);
    deepStrictEqual(SignatureSubpacket.encode(subpacket), encoded);
  });
  should('Signature subpacket supports expiration time fields', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const data = 86400;
    const cases = [
      { TAG: 'signatureExpirationTime' as const, tag: 3 },
      { TAG: 'keyExpirationTime' as const, tag: 9 },
    ];
    for (const c of cases) {
      const subpacket = { TAG: c.TAG, data };
      const encoded = concatBytes(Uint8Array.of(5, c.tag), U32BE(data));
      deepStrictEqual(SignatureSubpacket.decode(encoded), subpacket);
      deepStrictEqual(SignatureSubpacket.encode(subpacket), encoded);
    }
  });
  should('Signature subpacket supports notation and URI fields', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const name = utf8.decode('test@example.com');
    const value = utf8.decode('value');
    const notationBody = concatBytes(
      U32BE(0x80000000),
      U16BE(name.length),
      U16BE(value.length),
      name,
      value
    );
    const notation = {
      TAG: 'notationData' as const,
      data: { humanReadable: true, name: 'test@example.com', value },
    };
    const uriCases = [
      { TAG: 'preferredKeyServer' as const, tag: 24, data: 'https://keys.example.com' },
      { TAG: 'policyURI' as const, tag: 26, data: 'https://example.com/policy' },
    ];
    deepStrictEqual(
      SignatureSubpacket.decode(
        concatBytes(Uint8Array.of(1 + notationBody.length, 20), notationBody)
      ),
      notation
    );
    deepStrictEqual(
      SignatureSubpacket.encode(notation),
      concatBytes(Uint8Array.of(1 + notationBody.length, 20), notationBody)
    );
    for (const c of uriCases) {
      const encoded = concatBytes(
        Uint8Array.of(1 + utf8.decode(c.data).length, c.tag),
        utf8.decode(c.data)
      );
      const subpacket = { TAG: c.TAG, data: c.data };
      deepStrictEqual(SignatureSubpacket.decode(encoded), subpacket);
      deepStrictEqual(SignatureSubpacket.encode(subpacket), encoded);
    }
  });
  should('Signature subpacket supports reason for revocation', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const reason = 'retired';
    const subpacket = { TAG: 'reasonForRevocation' as const, data: { code: 3, reason } };
    const encoded = concatBytes(
      Uint8Array.of(2 + utf8.decode(reason).length, 29, 3),
      utf8.decode(reason)
    );
    deepStrictEqual(SignatureSubpacket.decode(encoded), subpacket);
    deepStrictEqual(SignatureSubpacket.encode(subpacket), encoded);
  });
  should('Signature subpacket supports exportable certification', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const nonExportable = { TAG: 'exportableCertification' as const, data: false, critical: true };
    const exportable = { TAG: 'exportableCertification' as const, data: true };
    deepStrictEqual(SignatureSubpacket.decode(Uint8Array.of(2, 0x84, 0)), nonExportable);
    deepStrictEqual(SignatureSubpacket.encode(nonExportable), Uint8Array.of(2, 0x84, 0));
    deepStrictEqual(SignatureSubpacket.decode(Uint8Array.of(2, 4, 1)), exportable);
    deepStrictEqual(SignatureSubpacket.encode(exportable), Uint8Array.of(2, 4, 1));
  });
  should('Signature subpacket supports deprecated revocation-key fields', () => {
    const { SignatureSubpacket } = pgp.__TESTS;
    const fingerprint = '05a9d616acfe6b2044ec28851dc754629725245b';
    const revocationKey = {
      TAG: 'revocationKey' as const,
      data: { class: 0x80, algo: 'EdDSA', fingerprint },
    };
    const revocable = { TAG: 'revocable' as const, data: false };
    deepStrictEqual(
      SignatureSubpacket.decode(
        concatBytes(Uint8Array.of(23, 12, 0x80, 22), hex.decode(fingerprint))
      ),
      revocationKey
    );
    deepStrictEqual(
      SignatureSubpacket.encode(revocationKey),
      concatBytes(Uint8Array.of(23, 12, 0x80, 22), hex.decode(fingerprint))
    );
    deepStrictEqual(SignatureSubpacket.decode(Uint8Array.of(2, 7, 0)), revocable);
    deepStrictEqual(SignatureSubpacket.encode(revocable), Uint8Array.of(2, 7, 0));
  });
  should('usage-255 encrypted secret-key checksum', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const before = structuredClone(secretKey);
    const { enc, S2K, iv } = secretKey.type.data;
    const keyLen = { aes128: 16, aes192: 24, aes256: 32 }[enc as 'aes128' | 'aes192' | 'aes256'];
    const kek = deriveKey(S2K.data.hash, keyLen, utf8.decode(PWD), S2K.data.salt, S2K.data.count);
    const clear = checksumSecret(seed);
    const secret = aesCfb(kek, iv, clear);
    const packet: SecretKey = {
      pub: secretKey.pub,
      type: { TAG: 'encrypted2', data: { enc, S2K, iv, secret } },
    };
    deepStrictEqual(pgp.decodeSecretKey(PWD, packet), bytesToBigInt(seed));
    deepStrictEqual(secretKey, before);
  });
  should('legacy direct-cipher secret-key packets decode but are not generated', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const before = structuredClone(secretKey);
    const enc = 'aes128';
    const iv = Uint8Array.from({ length: 16 }, (_, i) => i + 1);
    const clear = checksumOpaqueSecret(seed);
    const secret = aesCfb(md5(utf8.decode(PWD)), iv, clear);
    const data: SecretKey = {
      pub: secretKey.pub,
      type: { TAG: 'encryptedDirect', data: { enc, iv, secret } },
    };
    const body = concatBytes(pgp.PubKeyPacket.encode(secretKey.pub), Uint8Array.of(7), iv, secret);
    const raw = concatBytes(Uint8Array.of(0x94, body.length), body);
    const packet = [{ TAG: 'secretKey', data }];
    deepStrictEqual(pgp.Stream.decode(raw), packet);
    deepStrictEqual(pgp.Stream.encode(packet), raw);
    deepStrictEqual(pgp.decodeSecretKey(PWD, data), bytesToBigInt(seed));
    deepStrictEqual(
      pgp.privArmor
        .decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey)
        .filter((p) => p.TAG === 'secretKey' || p.TAG === 'secretSubkey')
        .map((p) => p.data.type.TAG),
      ['encrypted', 'encrypted']
    );
    deepStrictEqual(secretKey, before);
  });
  should('S2K derives long AES keys from concatenated hashes', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const before = structuredClone(secretKey);
    const { S2K, iv } = secretKey.type.data;
    const enc = 'aes256';
    const keyLen = 32;
    const kek = deriveKey(S2K.data.hash, keyLen, utf8.decode(PWD), S2K.data.salt, S2K.data.count);
    const keyBytes = pgp.opaquempi.encode(seed);
    const secret = aesCfb(kek, iv, concatBytes(keyBytes, sha1(keyBytes)));
    const packet: SecretKey = {
      pub: secretKey.pub,
      type: { TAG: 'encrypted', data: { enc, S2K, iv, secret } },
    };
    deepStrictEqual(pgp.decodeSecretKey(PWD, packet), bytesToBigInt(seed));
    deepStrictEqual(secretKey, before);
  });
  should('S2K decodes every parsed OpenPGP hash implementation', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const before = structuredClone(secretKey);
    const { iv } = secretKey.type.data;
    const salt = Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const hashes = ['md5', 'sha224', 'sha384', 'sha3_512'] as const;
    const decoded = hashes.map((hash) => {
      const S2K = { TAG: 'iterated' as const, data: { hash, salt, count: 96 } };
      const kek = deriveKey(hash, 16, utf8.decode(PWD), salt, 96);
      const keyBytes = pgp.opaquempi.encode(seed);
      const secret = aesCfb(kek, iv, concatBytes(keyBytes, sha1(keyBytes)));
      const packet: SecretKey = {
        pub: secretKey.pub,
        type: { TAG: 'encrypted', data: { enc: 'aes128', S2K, iv, secret } },
      };
      return [hash, pgp.decodeSecretKey(PWD, packet)] as const;
    });
    deepStrictEqual(decoded, [
      ['md5', bytesToBigInt(seed)],
      ['sha224', bytesToBigInt(seed)],
      ['sha384', bytesToBigInt(seed)],
      ['sha3_512', bytesToBigInt(seed)],
    ]);
    deepStrictEqual(secretKey, before);
  });
  should('encrypted secret-key IV length follows cipher block size', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const salt = Uint8Array.from([1, 2, 3, 4, 5, 6, 7, 8]);
    const iv = Uint8Array.from([9, 10, 11, 12, 13, 14, 15, 16]);
    const secret = Uint8Array.from([17, 18, 19, 20, 21, 22, 23, 24]);
    const S2K = { TAG: 'iterated', data: { hash: 'sha1', salt, count: 96 } };
    const data: SecretKey = {
      pub: secretKey.pub,
      type: { TAG: 'encrypted', data: { enc: 'tripledes', S2K, iv, secret } },
    };
    const body = concatBytes(
      pgp.PubKeyPacket.encode(secretKey.pub),
      Uint8Array.of(254, 2, 3, 2, ...salt, 96),
      iv,
      secret
    );
    const raw = concatBytes(Uint8Array.of(0x94, body.length), body);
    const packet = [{ TAG: 'secretKey', data }];
    deepStrictEqual(pgp.Stream.decode(raw), packet);
    deepStrictEqual(pgp.Stream.encode(packet), raw);
  });
  should('encrypted secret-key rejects plaintext cipher', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const malformed = structuredClone(secretKey);
    malformed.type.data.enc = 'plaintext';
    throws(() => pgp.decodeSecretKey(PWD, malformed), {
      name: 'Error',
      message: 'PGP.secretKey: unknown encryption mode=plaintext',
    });
  });
  should('encrypted secret-key rejects Argon2 S2K outside AEAD usage', () => {
    const packets = pgp.privArmor.decode(pgp.getKeys(seed, NAME_EMAIL, PWD, 0).privateKey);
    const secretKey = secretKeyPacket(packets);
    const salt = Uint8Array.from([
      0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
      0x0f,
    ]);
    const malformed = structuredClone(secretKey);
    malformed.type.data.S2K = { TAG: 'argon2', data: { salt, t: 1, p: 4, encodedM: 21 } };
    throws(() => pgp.Stream.encode([{ TAG: 'secretKey', data: malformed }]));
    const body = concatBytes(
      pgp.PubKeyPacket.encode(secretKey.pub),
      Uint8Array.of(254, 7, 4, ...salt, 1, 4, 21),
      secretKey.type.data.iv,
      secretKey.type.data.secret
    );
    const raw = concatBytes(Uint8Array.of(0xc5), pgp.PacketLen.encode(body.length), body);
    throws(() => pgp.Stream.decode(raw));
  });
  should('PGP Keys', () => {
    const { publicKey: pub } = pgp.getKeys(seed, NAME_EMAIL, PWD, 0);
    deepStrictEqual(
      pub,
      `-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEAAAAABYJKwYBBAHaRw8BAQdA2QIU3+eeQjGWpvS2/6iR3CbKu6iq+JbnM4HL
kyRFkfm0BWEgPGE+iJQEExYKADwWIQQzKMoIOBaUYqaTmfoamwl0PC4LXgUCAAAA
AAIbAwULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQGpsJdDwuC147OwEA
pgliM0hV4XfbsZMUyGci9pjsMRZO53tOobWdvhu8Gs8BAKwlB+XKCh9+kVBvxoZt
hHVBDgq0RFd26LRYHOg7bTcNuDgEAAAAABIKKwYBBAGXVQEFAQEHQBQ0JxdcnQhq
oDJmCZPdPTLT8aluxJBpIIqdZHOZBBk1AwEIB4h4BBgWCgAgFiEEMyjKCDgWlGKm
k5n6GpsJdDwuC14FAgAAAAACGwwACgkQGpsJdDwuC14bXgD/WBl23FKvTCTFnbt0
ltbVab4qEXPlSWkzfVyNGJfn9WsA/ja+yuocyI04UU8Wx5JK7iAlmFpnDmQtH6A6
fTxMaZcG
=6pnW
-----END PGP PUBLIC KEY BLOCK-----
`
    );
    const { publicKey: pub2 } = pgp.getKeys(seed, NAME_EMAIL, PWD, 123);
    deepStrictEqual(pub2 !== pub, true);
    deepStrictEqual(
      pub2,
      `-----BEGIN PGP PUBLIC KEY BLOCK-----

mDMEAAAAexYJKwYBBAHaRw8BAQdA2QIU3+eeQjGWpvS2/6iR3CbKu6iq+JbnM4HL
kyRFkfm0BWEgPGE+iJQEExYKADwWIQRnAFrpj5zsKWjJUsGjAb/LbAwBBwUCAAAA
ewIbAwULCQgHAgMiAgEGFQoJCAsCBBYCAwECHgcCF4AACgkQowG/y2wMAQee4gEA
qBdI8T8Dy1ImB1OtuBcnMq8xyV6iGn3LU5KFzn1AEzIA/3/FKasXRqLkQcDNXkqj
lWO1aZBR+SfRdBKhrNgPJOUOuDgEAAAAexIKKwYBBAGXVQEFAQEHQBQ0JxdcnQhq
oDJmCZPdPTLT8aluxJBpIIqdZHOZBBk1AwEIB4h4BBgWCgAgFiEEZwBa6Y+c7Clo
yVLBowG/y2wMAQcFAgAAAHsCGwwACgkQowG/y2wMAQebUwEAhzh0SQPNIoymV04j
oI1noKMUcAccBWq0IPXjfz3rUK0A/R04pwHhkHh4dBVDxoR3CyHYK9HRMXSZVBL1
jPfr1XwC
=HQ9C
-----END PGP PUBLIC KEY BLOCK-----
`
    );
    const maxTime = 2 ** 32 - 1;
    const maxTimeKeys = pgp.getKeys(seed, NAME_EMAIL, undefined, maxTime);
    deepStrictEqual(pgp.pubArmor.decode(maxTimeKeys.publicKey)[0].data.created, maxTime);
    deepStrictEqual(pgp.privArmor.decode(maxTimeKeys.privateKey)[0].data.pub.created, maxTime);
    throws(
      () => pgp.getKeys(seed, NAME_EMAIL, undefined, 2 ** 32),
      /invalid PGP key creation time/
    );
    // Cannot verify priv here since it has dynamic IV and stuff
  });
  should('Detached', () => {
    const pubKey = ed25519.getPublicKey(seed);
    const NAME = 'John Doe';
    const EMAIL = 'example@example.com';
    const FULL_NAME = `${NAME} <${EMAIL}>`;
    const keys = pgp.getKeys(seed, FULL_NAME, PWD, 0);
    // NOTE: signed as bytes!
    const commit = utf8.decode(
      'tree 4cf9f177c4c015836fca6a31f9c3917e89ae29ec\n' +
        'author John Doe <example@example.com> 0 +0000\n' +
        'committer John Doe <example@example.com> 0 +0000\n' +
        '\n' +
        'Initial commit\n'
    );
    const signature =
      '-----BEGIN PGP SIGNATURE-----\n' +
      '\n' +
      'iHUEABYKAB0WIQQzKMoIOBaUYqaTmfoamwl0PC4LXgUCAAAAAAAKCRAamwl0PC4L\n' +
      'Xi1HAP9YmLXuczZz1r8f2u7ouCjhVv/jCyyVKV0kS59NL6qadAD+LQNFbobvxs33\n' +
      'UB3Q9Co0hX0XOwmhTBxZX86oYz64AQQ=\n' +
      '=Lpwi\n' +
      '-----END PGP SIGNATURE-----\n';
    deepStrictEqual(pgp.signDetached(seed, commit, keys.fingerprint, 0), signature);
    deepStrictEqual(pgp.verifyDetached(pubKey, signature, commit, keys.fingerprint), true);
    const maxTime = 2 ** 32 - 1;
    const maxTimePacket = pgp.sigArmor.decode(
      pgp.signDetached(seed, commit, keys.fingerprint, maxTime)
    )[0].data;
    deepStrictEqual(maxTimePacket.head.hashed, [
      { TAG: 'issuerFingerprint', data: { version: undefined, fingerprint: keys.fingerprint } },
      { TAG: 'signatureCreationTime', data: maxTime },
    ]);
    throws(
      () => pgp.signDetached(seed, commit, keys.fingerprint, -1),
      /invalid PGP signature creation time/
    );
    throws(
      () => pgp.signDetached(seed, commit, keys.fingerprint, 1.5),
      /invalid PGP signature creation time/
    );
    throws(
      () => pgp.signDetached(seed, commit, keys.fingerprint, 2 ** 32),
      /invalid PGP signature creation time/
    );
    const helloSig = pgp.signDetached(seed, 'hello', keys.fingerprint, 0);
    const emptySig = pgp.signDetached(seed, '', keys.fingerprint, 0);
    deepStrictEqual(
      {
        hello: pgp.verifyDetached(pubKey, helloSig, 'hello', keys.fingerprint),
        helloLf: pgp.verifyDetached(pubKey, helloSig, 'hello\n', keys.fingerprint),
        empty: pgp.verifyDetached(pubKey, emptySig, '', keys.fingerprint),
        onlyLf: pgp.verifyDetached(pubKey, emptySig, '\n', keys.fingerprint),
      },
      {
        hello: true,
        helloLf: false,
        empty: true,
        onlyLf: false,
      }
    );
    const packets = pgp.sigArmor.decode(signature);
    const sha256Sig = signDetachedWithHash(seed, commit, keys.fingerprint, 'sha256');
    const sha1Sig = signDetachedWithHash(seed, commit, keys.fingerprint, 'sha1');
    const sha224Sig = signDetachedWithHash(seed, commit, keys.fingerprint, 'sha224');
    deepStrictEqual(pgp.verifyDetached(pubKey, sha256Sig, commit, keys.fingerprint), true);
    throws(() => pgp.verifyDetached(pubKey, sha1Sig, commit, keys.fingerprint), /digest/);
    throws(() => pgp.verifyDetached(pubKey, sha224Sig, commit, keys.fingerprint), /digest/);
    const [helloPacket] = pgp.sigArmor.decode(helloSig);
    const issuer = helloPacket.data.unhashed[0];
    const wrongIssuer = { TAG: 'issuer', data: '0000000000000000' };
    const issuerSig = (unhashed: SignatureSubpacket[]) =>
      pgp.sigArmor.encode([{ TAG: 'signature', data: { ...helloPacket.data, unhashed } }]);
    deepStrictEqual(
      {
        duplicate: pgp.verifyDetached(
          pubKey,
          issuerSig([...helloPacket.data.unhashed, issuer]),
          'hello',
          keys.fingerprint
        ),
        wrongOnly: pgp.verifyDetached(pubKey, issuerSig([wrongIssuer]), 'hello', keys.fingerprint),
        correctWrong: pgp.verifyDetached(
          pubKey,
          issuerSig([issuer, wrongIssuer]),
          'hello',
          keys.fingerprint
        ),
        wrongCorrect: pgp.verifyDetached(
          pubKey,
          issuerSig([wrongIssuer, issuer]),
          'hello',
          keys.fingerprint
        ),
      },
      {
        duplicate: true,
        wrongOnly: true,
        correctWrong: true,
        wrongCorrect: true,
      }
    );
    const issuerlessHead = {
      version: undefined,
      type: 'binary',
      algo: 'EdDSA',
      hash: 'sha512',
      hashed: [{ TAG: 'signatureCreationTime', data: 0 }],
    };
    const issuerlessData = Uint8Array.of(1, 2, 3);
    const issuerlessSigData = pgp.__TESTS.SignatureHead.encode(issuerlessHead);
    const issuerlessDigest = sha512(
      concatBytes(
        issuerlessData,
        issuerlessSigData,
        Uint8Array.of(0x04, 0xff),
        U32BE(issuerlessSigData.length)
      )
    );
    const issuerlessRaw = ed25519.sign(issuerlessDigest, seed);
    const issuerlessSig = pgp.sigArmor.encode([
      {
        TAG: 'signature',
        data: {
          head: issuerlessHead,
          unhashed: [],
          hashPrefix: issuerlessDigest.subarray(0, 2),
          sig: [
            bytesToBigInt(issuerlessRaw.subarray(0, 32)),
            bytesToBigInt(issuerlessRaw.subarray(32)),
          ],
        },
      },
    ]);
    deepStrictEqual(pgp.verifyDetached(pubKey, issuerlessSig, issuerlessData), true);
    throws(
      () => pgp.verifyDetached(pubKey, issuerlessSig, issuerlessData, keys.fingerprint),
      /wrong fingerprint/
    );
    const issuerOnlySig = pgp.sigArmor.encode([
      {
        TAG: 'signature',
        data: {
          head: issuerlessHead,
          unhashed: [{ TAG: 'issuer', data: keys.fingerprint.slice(-16) }],
          hashPrefix: issuerlessDigest.subarray(0, 2),
          sig: [
            bytesToBigInt(issuerlessRaw.subarray(0, 32)),
            bytesToBigInt(issuerlessRaw.subarray(32)),
          ],
        },
      },
    ]);
    deepStrictEqual(pgp.verifyDetached(pubKey, issuerOnlySig, issuerlessData), true);
    throws(
      () => pgp.verifyDetached(pubKey, issuerOnlySig, issuerlessData, keys.fingerprint),
      /wrong fingerprint/
    );
    const otherFingerprint = pgp.getKeyId(
      Uint8Array.from({ length: 32 }, (_, i) => i + 1),
      0
    ).fingerprint;
    const issuerFingerprintSig = (fingerprints: string[]) => {
      const head = {
        version: undefined,
        type: 'binary',
        algo: 'EdDSA',
        hash: 'sha512',
        hashed: [
          ...fingerprints.map((fingerprint) => ({
            TAG: 'issuerFingerprint',
            data: { version: undefined, fingerprint },
          })),
          { TAG: 'signatureCreationTime', data: 0 },
        ],
      };
      const sigData = pgp.__TESTS.SignatureHead.encode(head);
      const digest = sha512(
        concatBytes(issuerlessData, sigData, Uint8Array.of(0x04, 0xff), U32BE(sigData.length))
      );
      const raw = ed25519.sign(digest, seed);
      return pgp.sigArmor.encode([
        {
          TAG: 'signature',
          data: {
            head,
            unhashed: [],
            hashPrefix: digest.subarray(0, 2),
            sig: [bytesToBigInt(raw.subarray(0, 32)), bytesToBigInt(raw.subarray(32))],
          },
        },
      ]);
    };
    const wrongThenRightSig = issuerFingerprintSig([otherFingerprint, keys.fingerprint]);
    deepStrictEqual(pgp.verifyDetached(pubKey, wrongThenRightSig, issuerlessData), true);
    deepStrictEqual(
      pgp.verifyDetached(pubKey, wrongThenRightSig, issuerlessData, keys.fingerprint),
      true
    );
    const rightThenWrongSig = issuerFingerprintSig([keys.fingerprint, otherFingerprint]);
    deepStrictEqual(pgp.verifyDetached(pubKey, rightThenWrongSig, issuerlessData), true);
    throws(
      () => pgp.verifyDetached(pubKey, rightThenWrongSig, issuerlessData, keys.fingerprint),
      /wrong fingerprint/
    );
    packets[0].data.sig = [...packets[0].data.sig, 1n];
    throws(() => pgp.sigArmor.encode(packets));
    throws(() => pgp.sigArmor.decode(appendSignatureMPI(signature)));
    const withoutCreationTime = dropSignatureCreationTime(helloSig);
    const malformed = pgp.sigArmor.decode(helloSig);
    malformed[0].data.head.hashed = malformed[0].data.head.hashed.filter(
      (s) => s.TAG !== 'signatureCreationTime'
    );
    throws(() => pgp.sigArmor.decode(withoutCreationTime), /Signature Creation Time/);
    throws(() => pgp.sigArmor.encode(malformed), /Signature Creation Time/);
  });
  describe('parsePrivateKey', () => {
    should('basic', async () => {
      const NAME = 'John Doe';
      const EMAIL = 'example@example.com';
      const FULL_NAME = `${NAME} <${EMAIL}>`;
      const keys = pgp.getKeys(seed, FULL_NAME, undefined, 0);
      const parsed = await pgp.parsePrivateKey(keys.privateKey);
      deepStrictEqual(parsed.fingerprint, keys.fingerprint);
      deepStrictEqual(parsed.keyId, keys.keyId);
      deepStrictEqual(parsed.created, 0);
      deepStrictEqual(parsed.privateKey, seed);
    });
    should('password protected', async () => {
      const NAME = 'John Doe';
      const EMAIL = 'example@example.com';
      const FULL_NAME = `${NAME} <${EMAIL}>`;
      const keys = pgp.getKeys(seed, FULL_NAME, PWD, 123);
      await rejects(() => pgp.parsePrivateKey(keys.privateKey));
      const parsed = await pgp.parsePrivateKey(keys.privateKey, () => PWD);
      deepStrictEqual(parsed.fingerprint, keys.fingerprint);
      deepStrictEqual(parsed.keyId, keys.keyId);
      deepStrictEqual(parsed.created, 123);
      deepStrictEqual(parsed.privateKey, seed);
    });
  });
});

should.runWhen(import.meta.url);
